### ISSUE TITLE
Quick Settings: Clicking twice on the button open two dialog

### ISSUE THREAD

**Issue by Caceresenzo** [Caceresenzo/modern-rotation-control#2]

**Comment by Caceresenzo** [comment]
Both `Dialog.cancel()` and `Dialog.dismiss()` prevent the creation of a new dialog. We probably only have one "action token".

```
FATAL EXCEPTION: main (Ask Gemini)
Process: dev.caceresenzo.rotationcontrol, PID: 16881
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@2b595cc is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1823)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:600)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:150)
	at android.app.Dialog.show(Dialog.java:506)
	at android.service.quicksettings.TileService.showDialog(TileService.java:433)
	at dev.caceresenzo.rotationcontrol.RotationTileService.showDialog(RotationTileService.java:156)
	at dev.caceresenzo.rotationcontrol.RotationTileService.onClick(RotationTileService.java:87)
	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:806)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```
